databases:
  - name: prod-database
    databaseName: turbochat_production
    user: turbochat

services:
  - type: web
    name: prod-database
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false